Python 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 19:29:22) [MSC v.1916 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> 
================= RESTART: C:/Users/Chapa/Desktop/pruebas.py =================
Traceback (most recent call last):
  File "C:/Users/Chapa/Desktop/pruebas.py", line 1, in <module>
    import funciones.py
ModuleNotFoundError: No module named 'funciones.py'; 'funciones' is not a package
>>> 
================= RESTART: C:/Users/Chapa/Desktop/pruebas.py =================
Traceback (most recent call last):
  File "C:/Users/Chapa/Desktop/pruebas.py", line 3, in <module>
    prob_1(2)
NameError: name 'prob_1' is not defined
>>> 
================= RESTART: C:/Users/Chapa/Desktop/pruebas.py =================
Traceback (most recent call last):
  File "C:/Users/Chapa/Desktop/pruebas.py", line 3, in <module>
    prob_1(2)
NameError: name 'prob_1' is not defined
>>> 
================ RESTART: C:/Users/Chapa/Desktop/funciones.py ================
Traceback (most recent call last):
  File "C:/Users/Chapa/Desktop/funciones.py", line 8, in <module>
    prob_1()
TypeError: prob_1() missing 1 required positional argument: 'n'
>>> 
================ RESTART: C:/Users/Chapa/Desktop/funciones.py ================
>>> 
================ RESTART: C:/Users/Chapa/Desktop/funciones.py ================
prob_6(6)

